### ISSUE TITLE
Problem with <?php post_class(); ?>

### ISSUE THREAD

**Issue by ghost** [ajschlosser/wordpress-jade-template#1]
Thanks for great works.
I found a problem below.

jade:
article(id!="post-<?php the_ID(); ?>" class!="<?php post_class(); ?>")

php:
<article id="post-<?php the_ID(); ?>" class="<?php post_class(); ?>">

browser:
<article id="post-605" class="class=" post-605="" post="" type-post="" status-publish="" format-standard="" hentry="" category-34""="">

There is class=" class="" ".
Beause post_class() method generates code wraped by class="".

**Comment by ajschlosser** [comment]
Nice catch! I haven't looked at this repo in a while, so it might be a while before I update it again. Feel free to do whatever you like with it.
