### ISSUE TITLE
archive.jade

### ISSUE THREAD

**Issue by simonh1000** [ajschlosser/wordpress-jade-template#2]
When I compile archive.jade I am ending up with the following, which is crashing because it seems php expects to everything within one <?php ... ?> section. Are you not experiencing the same issue?

```
<h1>
<?php if ( is_day() ) { printf( __( 'Daily Archives: %s', 'template' ), get_the_time( get_option( 'date_format' ) ) ); } ?>
<?php elseif ( is_month() ) { printf( __( 'Monthly Archives: %s', 'template' ), get_the_time( 'F Y' ) ); } ?>
<?php elseif ( is_year() ) { printf( __( 'Yearly Archives: %s', 'template' ), get_the_time( 'Y' ) ); } ?>
<?php else { _e( 'Archives', 'template' ); } ?>
</h1>
```

I think I have the latest version of php on an ubuntu 14.10 machine

**Comment by ajschlosser** [comment]
I don't recall having that issue, no--have you been able to resolve it?

I'm not really maintaining this anymore, so feel free to do whatever you like with it...
